"""The Walk aggregate: state, events, evolver, and its two read paths."""

from aroc.execution.aggregates.walk.events import (
    WalkClaimed,
    WalkDispatched,
    WalkEnded,
    WalkEvent,
    WalkStepBroken,
    WalkStepDone,
    WalkStepRefused,
    WalkStepSkipped,
    from_stored,
    to_payload,
)
from aroc.execution.aggregates.walk.evolver import evolve, fold
from aroc.execution.aggregates.walk.read import (
    WALK_STREAM_TYPE,
    load_walk,
    load_walk_with_version,
)
from aroc.execution.aggregates.walk.state import (
    WALK_MAX_STEPS,
    WALK_PROCEDURE_NAME_MAX_LENGTH,
    WALK_STEP_MAX_LENGTH,
    InvalidStepReportError,
    InvalidWalkProcedureNameError,
    InvalidWalkStepsError,
    StepOutcome,
    Walk,
    WalkAlreadyEndedError,
    WalkAlreadyExistsError,
    WalkCannotBeClaimedError,
    WalkNotFoundError,
    WalkProcedureName,
    WalkStatus,
    WalkStep,
    WalkStepAlreadyReportedError,
    WalkStepOutOfRangeError,
    validated_steps,
)
from aroc.execution.aggregates.walk.summary import (
    WalkSummary,
    WalkSummaryLookup,
    WalkSummaryPage,
)

__all__ = [
    "WALK_MAX_STEPS",
    "WALK_PROCEDURE_NAME_MAX_LENGTH",
    "WALK_STEP_MAX_LENGTH",
    "WALK_STREAM_TYPE",
    "InvalidStepReportError",
    "InvalidWalkProcedureNameError",
    "InvalidWalkStepsError",
    "StepOutcome",
    "Walk",
    "WalkAlreadyEndedError",
    "WalkAlreadyExistsError",
    "WalkCannotBeClaimedError",
    "WalkClaimed",
    "WalkDispatched",
    "WalkEnded",
    "WalkEvent",
    "WalkNotFoundError",
    "WalkProcedureName",
    "WalkStatus",
    "WalkStep",
    "WalkStepAlreadyReportedError",
    "WalkStepBroken",
    "WalkStepDone",
    "WalkStepOutOfRangeError",
    "WalkStepRefused",
    "WalkStepSkipped",
    "WalkSummary",
    "WalkSummaryLookup",
    "WalkSummaryPage",
    "evolve",
    "fold",
    "from_stored",
    "load_walk",
    "load_walk_with_version",
    "to_payload",
    "validated_steps",
]
